[workspace]
members = [
    "ast",
    "compiler",
    "west_error",
    "lexer",
    "parser",
    "typechecker",
    "vm",
    "west",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
west_error = { path = "west_error" }
vm = { path = "vm" }
compiler = { path = "compiler" }
typechecker = { path = "typechecker" }
ast = { path = "ast" }
parser = { path = "parser" }
lexer = { path = "lexer" }

thiserror = { version = "2" }
miette = { version = "7.4.0", features = ["fancy"] }
