[workspace]
members = ["ast", "lexer", "parser", "west"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
parser = { path = "parser" }
ast = { path = "ast" }
lexer = { path = "lexer" }

miette = { version = "7.4.0", features = ["fancy"] }
