[workspace]
members = ["ast", "compiler", "lexer", "parser", "vm", "west"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
compiler = { path = "compiler" }
vm = { path = "vm" }
parser = { path = "parser" }
ast = { path = "ast" }
lexer = { path = "lexer" }

thiserror = { version = "2" }
miette = { version = "7.4.0", features = ["fancy"] }
