[package]
name = "typechecker"
version.workspace = true
edition.workspace = true

[dependencies]
west_error.workspace = true
parser.workspace = true
ast.workspace = true

miette.workspace = true
thiserror.workspace = true
