[package]
name = "parser"
version.workspace = true
edition.workspace = true

[dependencies]
west_error.workspace = true
lexer.workspace = true
ast.workspace = true

miette.workspace = true
thiserror.workspace = true
