[package]
name = "compiler"
version.workspace = true
edition.workspace = true

[dependencies]
west_error.workspace = true
ast.workspace = true
parser.workspace = true
vm.workspace = true

miette.workspace = true
thiserror.workspace = true
