[package]
name = "compiler"
version.workspace = true
edition.workspace = true

[dependencies]
typechecker.workspace = true
west_error.workspace = true
ast.workspace = true
parser.workspace = true

inkwell.workspace = true
miette.workspace = true
thiserror.workspace = true
