[package]
name = "west"
version.workspace = true
edition.workspace = true

[dependencies]
parser.workspace = true
vm.workspace = true

miette.workspace = true

clap = { version = "4.5.26", features = ["derive"] }
