[package]
name = "west"
version.workspace = true
edition.workspace = true

[dependencies]
fout.workspace = true
typechecker.workspace = true
vm.workspace = true
parser.workspace = true
compiler.workspace = true

clap = { version = "4.5.26", features = ["derive"] }
ariadne.workspace = true
